### ISSUE TITLE
Multiple Edit Sessions to create system Resources

### ISSUE THREAD

**Issue by naragani** [magnuswatn/wls-rest-python#2]
Hello Magnus (@magnuswatn ) ,

Thank  you for the wls-rest-python work , it is working fine for us for simple projects us , but we are having hard time to understand when multiple edit sessions required to create a resource , like JDBC resource. We tried with helper class , but did not succeed .

 Do you have a sample to create JDBCresource as explained in below link with multiple curl commands ? , I am interested to check how we can use dynamic URLs to post the data uisng wls-rest-pyton  for eg. create  a data source and in the same edit session we need to configure the datasource parameters and  connection pool parameters  as explained in below link with curl .
https://docs.oracle.com/middleware/12213/wls/WLRUR/examples.htm#WLRUR199

Previous version with /management/wls  we have working script ,but /management/wls is deprecated in new version , we need dynamic urls with multiple edit sessions required with new REST API to configure system resources , I would really appreciate if you could help how  to re-use wls_rest_python  to create system resources . 

Thank you 
Kumar

**Comment by magnuswatn** [comment]
Hi,

Sorry for the late reply. You can start a change session, and active it, using the change manager, like so:
```
wls.edit.changeManager.startEdit()
wls.edit.changeManager.activate()
```

In that Oracle example, they use `saveChanges=false` which I haven't seen before, but since wls-rest-python is using requests behind the scenes, we can just use the `params` param. So that example would look something like this:

```
# Start editing
change_manager = wls.edit.changeManager
change_manager.startEdit()


# Create a new global JDBC system resource and set its name
wls.edit.JDBCSystemResources.create(
    json={
        "name": "JDBCDataSource1",
        "targets": [{"identity": ["clusters", "Cluster1"]}],
    },
    params={"saveChanges": False},
)

jdbc_resource = wls.edit.JDBCSystemResources.JDBCDataSource1.JDBCResource
jdbc_resource.update(name="JDBCDataSource1")

# Configure the JDBC system resource's JNDI name
jdbc_resource.JDBCDataSourceParams.update(JNDINames=["JDBCDataSource1"])

# Configure the JDBC system resource's driver info
jdbc_params = jdbc_resource.JDBCDriverParams
jdbc_params.update(
    driverName="org.apache.derby.jdbc.ClientXADataSource",
    url="jdbc:derby://localhost:1527/demo",
)

jdbc_params.properties.properties.update(name="portNumber", value="1527")

jdbc_params.properties.properties.update(name="databaseName", value="demo;create=true")

jdbc_params.properties.properties.update(name="serverName", value="localhost")

# Activate the changes
change_manager.activate()
```

Does this help you?

**Comment by naragani** [comment]
Thank you  magnus . I found after further research and was able to over come this issue . But I really appreciate you gettting back to me .  I was able to figure out my self about multiple edit sessions issue,but  following 2 lines of codes opened the opportunities to explore more on this , I tried to create jms resources and had hard time to create multiple resources with wls.edit , I will try to get the object of wls.edit.JMSSystemresources and will try that . 

jdbc_resource = wls.edit.JDBCSystemResources.JDBCDataSource1.JDBCResource
jdbc_resource.update(name="JDBCDataSource1")

Thanks a TON !!!
-Kumar
