### ISSUE TITLE
Deploy a "server-side" application, no upload requiered

### ISSUE THREAD

**Issue by mjakob-gh** [magnuswatn/wls-rest-python#3]
I am trying to deploy an application where the ear file is already on the server (so no upload requiered). I also dont want to use a seperate plan xml file.
Oracle has this example https://docs.oracle.com/middleware/1221/wls/WLRUR/examples.htm#WLRUR200 (Synchronously deploy a domain-scoped server-side application to the cluster)

can i achieve this with wls-rest-python?

I already tried this naive approach:

`wls.edit.appDeployments.create(wls_deployment)`

where wls_deployment looks like this:
```
wls_deployment = {
    'name': 'demoapp',
    'sourcePath': '/opt/deploy/demoapp.war',
    'targets': [ {'identity': [ 'servers', 'test-a1' ] } ]
}
```

The server seems to expect the file to be uploaded, instead reading  it from the filesystem.

**Comment by magnuswatn** [comment]
Seems correct, but you have to send it as json. Try this:
```
wls.edit.appDeployments.create(json=wls_deployment)
```

**Comment by mjakob-gh** [comment]
Thank you, your suggestions works.

Is there a way, to see what is expected by the methods? Is it maybe the Content-type in the examples on the Oracle Site (see above)?

This example "Synchronously deploy a domain-scoped server-side application to the cluster" has
`Content-Type:application/json`
does it mean, send it as json?

The example "Asynchronously upload a domain-scoped application from the client and deploy it to the cluster" has:
`Content-Type:multipart/form-data`
does it mean, send it as file?
